// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmn1XHuPh3zFgWgJxXbUCEFrsKsmPAlVY',
    appId: '1:257523151411:web:a771127640b8f0db83a946',
    messagingSenderId: '257523151411',
    projectId: 'easy-shoping-d9025',
    authDomain: 'easy-shoping-d9025.firebaseapp.com',
    storageBucket: 'easy-shoping-d9025.firebasestorage.app',
    measurementId: 'G-1X7179YCES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfQmG2upi9zd1Do94Wzbj131VdDkGk0fg',
    appId: '1:257523151411:android:55d1eebd5c2484aa83a946',
    messagingSenderId: '257523151411',
    projectId: 'easy-shoping-d9025',
    storageBucket: 'easy-shoping-d9025.firebasestorage.app',
  );
}
